baseURL = "https://casey-oneill.github.io/"
author = "Casey O'Neill"
copyright = "Copyright © 2024, Casey O'Neill; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

# ------------------------------
theme = "paper"
title = "Casey O'Neill"

[params]
color = 'linen'

github = 'casey-oneill'
linkedin = 'caseyoneill'

avatar = '/images/Profile.png'
name = "Hi, I'm Casey!"
bio = "I'm a Human-Computer Interaction graduate student at the University of Waterloo. This is my personal website, where you can find information about me and read my blog posts."

monoDarkIcon = true
# ------------------------------

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "publications"
name = "Publications"
url = "/publications/"
weight = 10
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 10
[[menu.main]]
identifier = "cv"
name = "CV"
url = "/cv/"
weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true
